version: '2.1'

services:

  admin:
    restart: always
    image: "quay.io/basis-company/tarantool-admin"
    ports:
      - "8000:80"
    volumes:
      - ./php:/var/www/html/php
      - ./public/admin/js:/var/www/html/admin/js
      - ./public/admin/index.php:/var/www/html/admin/index.php
      - ./public/admin/style.css:/var/www/html/admin/style.css

  tarantool:
    image: "tarantool/tarantool:1"
    restart: always
    ports:
      - "3301:3301"
    healthcheck:
      test: tarantool_is_up
      interval: 60s
      timeout: 15s
      retries: 10
